---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-gateway
spec:
  defaultBackend:
    service:
      name: loki-gateway
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - loki
