---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: loki-config-env
  namespace: {{ include "lokiConfig.namespace" . }}
spec:
  itemPath: "vaults/{{ .Values.onePassword.vault }}/items/{{ .Values.onePassword.itemName }}"
