name: evedata_monorepo

config-version: 2
version: "1.0"

profile: evedata

model-paths: ["models"]
snapshot-paths: ["snapshots"]

vars:
  "dbt_date:time_zone": "UTC"

models:
  evedata:
    intermediate:
      +materialized: view
      +schema: int
    marts:
      +schema: marts
      +materialized: table
    staging:
      +materialized: view
      +schema: stg

dispatch:
  - macro_namespace: dbt
    search_order: ["dbt_project_evaluator", "dbt"]

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
