---
# defaults file for tailscale_operator role
# Default variables for Tailscale Operator deployment

# Helm Configuration
# Path to kubeconfig file for Helm operations (defined in group_vars/all.yml)
# helm_kubeconfig: /var/snap/microk8s/current/credentials/client.config

# Namespace configuration
tailscale_operator_namespace: tailscale
tailscale_operator_create_namespace: true

# Helm repository configuration
tailscale_operator_helm_repo_name: tailscale
tailscale_operator_helm_repo_url: https://pkgs.tailscale.com/helmcharts

# Helm release configuration
tailscale_operator_release_name: tailscale-operator
tailscale_operator_chart_version: "" # Empty string means latest version

# API server proxy configuration
# Set to true for auth mode (impersonation), "noauth" for noauth mode
tailscale_operator_api_server_proxy_mode: true

# Operator configuration
tailscale_operator_replica_count: 1
tailscale_operator_image_pull_policy: IfNotPresent
tailscale_operator_log_level: info

# Operator image configuration
# Pinning to specific versions ensures reproducible deployments
tailscale_operator_image_tag: v1.88.4
tailscale_operator_image_digest: sha256:9a35d316344e4d6f85733848e79947566132d16abdb5fefb60adc49e04b9745c

# Proxy image configuration
# Pinning to specific versions ensures reproducible deployments
tailscale_operator_proxy_image_tag: v1.88.4
tailscale_operator_proxy_image_digest: sha256:d3628e624f0978a126c89b6b500f2baec9a7386b468635cebeb3f950f7575188

# Additional Helm values to pass to the chart
# This will be merged with the values generated by the role
tailscale_operator_extra_values: {}
# Required variables (must be provided by user)
# tailscale_operator_oauth_client_id: ""
# tailscale_operator_oauth_client_secret: ""
# tailscale_operator_hostname: ""

# DNS configuration
# MagicDNS nameserver configuration for in-cluster DNS resolution
tailscale_operator_dns_nameserver_repo: tailscale/k8s-nameserver
tailscale_operator_dns_nameserver_tag: unstable
