---
apiVersion: v2
name: services-core-loki-config
description: Configuration for Loki.
type: application
version: 1.0.0
appVersion: "1.0"
maintainers:
  - name: EVEData Team
home: https://github.com/evedata/evedata
sources:
  - https://github.com/evedata/evedata/tree/main/deploy/argocd/services/core/loki-config
annotations:
  app.kubernetes.io/name: services-core-loki-config
  app.kubernetes.io/component: core
