---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "loki.gatewayFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.gatewayLabels" . | nindent 4 }}
    {{- range $labelKey, $labelValue := .Values.loki.gateway.ingress.labels }}
    {{ $labelKey }}: {{ $labelValue | toYaml }}
    {{- end }}
  {{- with .Values.loki.gateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: {{ include "loki.gatewayFullname" . }}
      port:
        number: 80
  tls:
    {{- range .Values.loki.gateway.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
    {{- end }}
  rules:
    {{- range .Values.loki.gateway.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "loki.gatewayFullname" $ }}
                port:
                  number: {{ $.Values.loki.gateway.service.port }}
          {{- end }}
    {{- end }}
