---
{{- if and .Values.gateway.enabled -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "loki.onePasswordItemFullname" . }}
  namespace: {{ include "loki.namespace" . }}
spec:
  itemPath: "vaults/{{ .Values.onePasswordItem.vault }}/items/{{ include "loki.storageOnePasswordItemFullname" . }}"
{{- end }}
