name: evedata

config-version: 2
version: "1.0"

profile: evedata

model-paths: ["models"]
snapshot-paths: ["snapshots"]

vars:
  "dbt_date:time_zone": "UTC"

models:
  evedata:
    +database: lake
    +materialized: view

    staging:
      +tags: ["staging"]
      hde:
        +schema: hde
        +tags: ["hde"]
      sde:
        +schema: sde
        +tags: ["sde"]

dispatch:
  - macro_namespace: dbt
    search_order: ["dbt_project_evaluator", "dbt"]

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
