name: evedata

config-version: 2
version: "1.0"

profile: evedata

model-paths: ["models"]
snapshot-paths: ["snapshots"]

vars:
  "dbt_date:time_zone": "UTC"

models:
  evedata:
    intermediate:
      +database: lake
      +materialized: view
      +schema: int
      +tags: ["silver", "intermediate"]
    marts:
      +database: lake
      +schema: marts
      +materialized: table
      +tags: ["gold", "marts"]
    staging:
      +database: lake
      +materialized: view
      +schema: stg
      +tags: ["bronze", "staging"]

dispatch:
  - macro_namespace: dbt
    search_order: ["dbt_project_evaluator", "dbt"]

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
