#!/bin/bash

set -e

source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw _dlt_loads &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw _dlt_pipeline_state &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw _dlt_version &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw agent_types &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw agents_in_space &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw ancestries &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw bloodlines &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__copying__materials &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__copying__skills &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__invention__materials &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__invention__products &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__invention__skills &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__manufacturing__materials &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__manufacturing__products &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__manufacturing__skills &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__reaction__materials &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__reaction__products &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__reaction__skills &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__research_material__materials &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__research_material__skills &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__research_time__materials &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw blueprints__activities__research_time__skills &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw categories &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw certificates &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw certificates__recommended_for &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw certificates__skill_types &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw character_attributes &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw contraband_types &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw contraband_types__factions &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw control_tower_resources &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw control_tower_resources__resources &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw corporation_activities &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dbuff_collections &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dbuff_collections__item_modifiers &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dbuff_collections__location_group_modifiers &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dbuff_collections__location_modifiers &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dbuff_collections__location_required_skill_modifiers &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dogma_attribute_categories &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dogma_attributes &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dogma_effects &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dogma_effects__modifier_info &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dogma_units &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dynamic_item_attributes &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dynamic_item_attributes__attribute_ids &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dynamic_item_attributes__input_output_mapping &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw dynamic_item_attributes__input_output_mapping__applicable_types &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw factions &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw factions__member_races &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw graphics &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw graphics__sof_layout &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw groups &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw icons &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw landmarks &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_asteroid_belts &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_constellations &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_constellations__solar_system_ids &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_moons &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_moons__npc_station_ids &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_planets &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_planets__asteroid_belt_ids &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_planets__moon_ids &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_planets__npc_station_ids &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_regions &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_regions__constellation_ids &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_solar_systems &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_solar_systems__disallowed_anchor_categories &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_solar_systems__disallowed_anchor_groups &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_solar_systems__planet_ids &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_solar_systems__stargate_ids &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_stargates &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw map_stars &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw market_groups &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw masteries &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw masteries___value &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw masteries___value___value &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw meta_groups &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_characters &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_characters__skills &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_corporation_divisions &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_corporations &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_corporations__allowed_member_races &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_corporations__corporation_trades &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_corporations__divisions &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_corporations__exchange_rates &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_corporations__investors &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_corporations__lp_offer_tables &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw npc_stations &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw planet_resources &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw planet_schematics &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw planet_schematics__pins &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw planet_schematics__types &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw races &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw races__skills &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw skin_licenses &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw skin_materials &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw skins &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw skins__types &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw sovereignty_upgrades &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw station_operations &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw station_operations__services &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw station_operations__station_types &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw station_services &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw translation_languages &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_bonus &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_bonus__misc_bonuses &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_bonus__role_bonuses &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_bonus__types &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_bonus__types___value &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_dogma &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_dogma__dogma_attributes &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_dogma__dogma_effects &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_materials &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw type_materials__materials &&
source dbt_packages/codegen/bash_scripts/base_model_creation.sh sde_raw types
