name = "evedata-docs"
compatibility_date = "2025-04-01"
preview_urls = true

[env.dev]
name = "evedata-docs-dev"

[env.prd]
name = "evedata-docs-prd"
route = { pattern = "docs.evedata.io", custom_domain = true }

[env.stg]
name = "evedata-docs-stg"
route = { pattern = "docs-stg.evedata.dev", custom_domain = true }

[assets]
directory = "./site"
not_found_handling = "404-page"
