---
# Credentials handling tasks for 1Password Connect

- name: Upload 1Password Connect credentials file
  ansible.builtin.copy:
    src: "{{ op_connect_credentials_file }}"
    dest: "{{ op_connect_credentials_upload_path }}"
    mode: "0600"
    owner: root
    group: root
    backup: false
  become: true
  no_log: true
  tags:
    - op-connect
    - op-connect-credentials

- name: Verify credentials file exists on target
  ansible.builtin.stat:
    path: "{{ op_connect_credentials_upload_path }}"
  register: op_connect_credentials_stat
  become: true
  failed_when: not op_connect_credentials_stat.stat.exists
  tags:
    - op-connect
    - op-connect-credentials

- name: Verify credentials file permissions
  ansible.builtin.assert:
    that:
      - op_connect_credentials_stat.stat.mode == '0600'
      - op_connect_credentials_stat.stat.uid == 0
      - op_connect_credentials_stat.stat.gid == 0
    fail_msg: "Credentials file does not have correct permissions (should be 0600, owner/group root)"
  when: op_connect_credentials_stat.stat.exists
  tags:
    - op-connect
    - op-connect-credentials
