---
# Secret creation tasks for Cloudflare Tunnel using 1Password

- name: Check if OnePasswordItem CRD exists
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: onepassworditems.onepassword.com
    kubeconfig: "{{ helm_kubeconfig }}"
  register: onepassword_crd_check
  become: true
  failed_when: false
  tags:
    - cloudflared
    - cloudflared-secret

- name: Fail if OnePasswordItem CRD not found
  ansible.builtin.fail:
    msg: >-
      OnePasswordItem CRD not found. Please ensure the 1Password Operator is installed.
      Run the op_connect role first to install the operator.
  when: onepassword_crd_check.resources | length == 0
  tags:
    - cloudflared
    - cloudflared-secret

- name: Create OnePasswordItem for Cloudflare Tunnel token
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ helm_kubeconfig }}"
    definition:
      apiVersion: onepassword.com/v1
      kind: OnePasswordItem
      metadata:
        name: "{{ cloudflared_secret_name }}"
        namespace: "{{ cloudflared_namespace }}"
        labels:
          app: cloudflared
          "app.kubernetes.io/name": cloudflared
          "app.kubernetes.io/component": secret
          "app.kubernetes.io/managed-by": ansible
      spec:
        itemPath: "vaults/{{ op_connect_vault }}/items/{{ cloudflared_secret_name }}"
  become: true
  no_log: true # Prevent logging sensitive information
  tags:
    - cloudflared
    - cloudflared-secret

- name: Wait for OnePasswordItem to be processed
  kubernetes.core.k8s_info:
    api_version: onepassword.com/v1
    kind: OnePasswordItem
    name: "{{ cloudflared_secret_name }}"
    namespace: "{{ cloudflared_namespace }}"
    kubeconfig: "{{ helm_kubeconfig }}"
  register: onepassword_item_status
  become: true
  until:
    - onepassword_item_status.resources | length > 0
    - onepassword_item_status.resources[0].status is defined
  retries: 30
  delay: 2
  tags:
    - cloudflared
    - cloudflared-secret

- name: Verify secret was created by 1Password Operator
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ cloudflared_secret_name }}"
    namespace: "{{ cloudflared_namespace }}"
    kubeconfig: "{{ helm_kubeconfig }}"
  register: cloudflared_secret_check
  become: true
  failed_when: cloudflared_secret_check.resources | length == 0
  tags:
    - cloudflared
    - cloudflared-secret

- name: Display secret status
  ansible.builtin.debug:
    msg:
      - "OnePasswordItem '{{ cloudflared_secret_name }}' created successfully"
      - "Secret '{{ cloudflared_secret_name }}' available in namespace '{{ cloudflared_namespace }}'"
      - "Secret data keys: {{ cloudflared_secret_check.resources[0].data.keys() | list }}"
  tags:
    - cloudflared
    - cloudflared-secret
