name: Terraform
on:
  push:
    branches:
      - main
    paths:
      - "infra/terraform/**"
  pull_request:
    branches:
      - main
    paths:
      - "infra/terraform/**"
  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Deployment target"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
          - both

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  UV_CACHE_DIR: .uv_cache
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - working-directory: infra
        run: make lint-terraform
